# Generated by Django 5.2.1 on 2025-06-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reorder_level',
            field=models.IntegerField(default=5),
        ),
    ]
